version: '3.3'

volumes:
  postgres_data:

services:
  db:
    image: postgres:17
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    restart: always
  api:
    build:
      context: ./
    env_file:
      - .env
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./:/app/
    command: sh -c "alembic upgrade head && cd application && sanic main.app --host=0.0.0.0 --port=8000"
    depends_on:
      db:
        condition: "service_healthy"
    restart: always
